spring:
  cloud:
    azure:
      eventhubs:
        namespace: 'sef-audit'
        processor:
          checkpoint-store:
            container-name: 'seffilesystem'
            account-name:  'sefstorageaccount'
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: 'audit'
          group: 'audit-cg'
        supply-out-0:
          destination: 'audit' # same as the above destination
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
